/**
 * scripts/csv-to-json.js
 * Run: node scripts/csv-to-json.js
 *
 * Reads folkcharm_product_emission_lookup.csv from the project root
 * and writes src/data/lookup.js with a JS export.
 *
 * Usage:
 *   1. Place folkcharm_product_emission_lookup.csv in the project root.
 *   2. node scripts/csv-to-json.js
 *   3. Commit the updated src/data/lookup.js
 */

const fs = require("fs");
const path = require("path");

const CSV_PATH = path.join(__dirname, "..", "folkcharm_product_emission_lookup.csv");
const OUT_PATH = path.join(__dirname, "..", "src", "data", "lookup.js");

function parseCSV(content) {
  const lines = content.trim().split("\n");

  // split by comma
  const headers = lines[0].split(",").map((h) => h.trim());

  return lines.slice(1).map((line) => {
    const values = line.split(",");

    const row = {};

    headers.forEach((header, i) => {
      const val = (values[i] || "").trim();

      const numericFields = [
        "size_factor",
        "gsm",
        "metres_per_unit",
        "fabric_kg_per_unit",
        "E_transport",
        "E_electricity",
        "E_water",
        "E_tailoring",
        "E_total_kg_co2e",
        "avoided_kg_co2e",
      ];

      row[header] = numericFields.includes(header)
        ? parseFloat(val) || 0
        : val;
    });

    return row;
  });
}

const raw = fs.readFileSync(CSV_PATH, "utf8");
const data = parseCSV(raw);

const output = `/**
 * Folkcharm URD-202 — Product Emission Lookup
 * Methodology v2.2
 * Auto-generated by scripts/csv-to-json.js — do not edit manually.
 * Last generated: ${new Date().toISOString()}
 */

const lookup = ${JSON.stringify(data, null, 2)};

export default lookup;
`;

fs.writeFileSync(OUT_PATH, output, "utf8");
console.log(`✅ Written ${data.length} rows to ${OUT_PATH}`);
